<?php

namespace Farpost\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ScheduleSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleSourceRepository extends EntityRepository
{
   private function _prepareQB()
   {
      $qb = $this->_em->createQueryBuilder();
      $qb->select('ssrc')->distinct()->from('FarpostStoreBundle:ScheduleSource', 'ssrc');
      $subquery = $this->_em->createQueryBuilder()
                       ->select('count(a.id)')
                       ->from('FarpostStoreBundle:ScheduleSource', 'a')
                       ->where('a.group = ssrc.group')
                       ->andWhere('a.v_datetime > ssrc.v_datetime');
      $qb->where('(' . $subquery->getDQL() . ') = 0');
      return $qb;
   }

   private function _finalizeWeb(&$recs) {
      $result = [];
      foreach($recs as $rec) {
         $elem = [
            "group" => $rec->getGroup()->getAlias(),
            "vdt" => date('d-m-Y, G:i:s', $rec->getVDatetime())
         ];
         array_push($result, $elem);
      }
      return $result;
   }

   public function getForWeb()
   {
      $recs = $this->_prepareQB()->getQuery()->getResult();
      return $this->_finalizeWeb($recs);
   }

   public function getLastRecords()
   {
      return $this->_prepareQB()->getQuery()->getResult();
   }
}
