#!/bin/bash
#app/console doctrine:database:drop --force;
#app/console doctrine:database:create;
#app/console doctrine:generate:entities --no-backup Farpost;
#app/console doctrine:schema:update --force --em=default;
#app/console cache:warmup --env=prod --no-debug
#php scripts/FillDb.php
