imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @FarpostCatalogueBundle/Resources/config/admin.yml }
    - { resource: @FarpostMapsBundle/Resources/config/admin.yml }
    - { resource: @FarpostNewsBundle/Resources/config/admin.yml }
    - { resource: @FarpostPOIBundle/Resources/config/admin.yml }

services:
    entity_dispatcher:
        class: Farpost\StoreBundle\Services\EntityDispatcher
    sqlite_manager:
        class: Farpost\StoreBundle\Services\SQLiteManager
    schedule_manager:
        class: Farpost\StoreBundle\Services\ScheduleManager
        arguments: [ @doctrine, "@session" ]
    database_converter:
        class: Farpost\StoreBundle\Services\DatabaseConverter
        arguments: [ @doctrine, "@sqlite_manager", "@entity_dispatcher", "@schedule_manager" ]
    sql_booster:
        class: Farpost\StoreBundle\Services\sql_booster
        arguments: [ @doctrine ]
    api_helper:
        class: Farpost\APIBundle\Services\APIHelper
        arguments: [ @doctrine ]

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: 
        enabled: false
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    cache:            false
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'SonataCoreBundle:Form:datepicker.html.twig'
            - 'SonataMediaBundle:Form:media_widgets.html.twig'
#    form_themes:
#        - 'FarpostMapsBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
        default_connection: default
        connections:
            default:
                driver:   "%default_database_driver%"
                host:     "%default_database_host%"
                port:     "%default_database_port%"
                dbname:   "%default_database_name%"
                user:     "%default_database_user%"
                password: "%default_database_password%"
                logging: false
                profiling: false
            back_up:
                driver:   "%backup_database_driver%"
                host:     "%backup_database_host%"
                port:     "%backup_database_port%"
                dbname:   "%backup_database_name%"
                user:     "%backup_database_user%"
                password: "%backup_database_password%"
                logging: false
                profiling: false

        #ahjihaR1eeQu
        #Xt4Mc5hm$v

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    FarpostCatalogueBundle: ~
                    FarpostStoreBundle: ~
                    FarpostMapsBundle: ~
                    FarpostNewsBundle: ~
                    FarpostPOIBundle: ~
                    SonataMediaBundle: ~
                    ApplicationSonataMediaBundle: ~
            back_up:
                connection: back_up
                mappings:
                    FarpostBackUpBundle: ~
            documents:
                connection: default
                mappings:
                    FarpostStoreBundle: ~

#sonata
sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text: ~
        sonata.block.service.action: ~
        sonata.block.service.versions: ~
        sonata.block.service.graph_importer: ~
        sonata.block.service.editor: ~
        # Your other blocks

sonata_admin:
    title: Кампус Гид
    templates:
        dashboard: SonataAdminBundle:Core:dashboard.html.twig
    assets:
        stylesheets:
            - bundles/sonataadmin/vendor/bootstrap/dist/css/bootstrap.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/font-awesome.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/ionicons.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/AdminLTE.css
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
            - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
            - bundles/sonataadmin/vendor/select2/select2.css
            - bundles/sonataadmin/vendor/select2/select2-bootstrap.css
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/layout.css
            - bundles/farpostcatalogue/css/custom.css
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
            - { position: right, type: sonata.block.service.graph_importer }
            - { position: right, type: sonata.block.service.versions }
            - { position: left, type: sonata.block.service.editor }


sonata_doctrine_orm_admin:
    # default value is null, so doctrine uses the value defined in the configuration
    entity_manager: ~

sonata_media:
    default_context: default
    db_driver: doctrine_orm
    contexts:
        default:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
            formats:
                small: { width: 100, quality: 70 }
                big:   { width: 500, quality: 70 }
        news:
            providers:
                - sonata.media.provider.image
            formats:
                preview: { width: 100, quality: 100 }
                small: { width: 100, quality: 100 }
                big:   { width: 500, quality: 100 }
        catalogue:
            providers:
                - sonata.media.provider.image
            formats:
                thumbnail: { height: 200, quality: 100 }
        icons:
            providers:
                - sonata.media.provider.image
            formats:
                icon: { width: 75, quality: 100 }

    cdn:
        server:
            path: /uploads/media

    filesystem:
        local:
            directory: %kernel.root_dir%/../web/uploads/media
            create: true


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }