farpost_back_up:
    resource: "@FarpostBackUpBundle/Resources/config/routing.yml"
    prefix:   /

farpost_web:
    resource: "@FarpostWebBundle/Resources/config/routing.yml"
    prefix:   /web/

farpost_admin:
    resource: "@FarpostWebBundle/Resources/config/admin_routing.yml"
    prefix:   /admin/

farpost_api:
    resource: "@FarpostAPIBundle/Resources/config/routing.yml"
    prefix:   /method/

farpost_test:
    resource: "@FarpostTestBundle/Resources/config/routing.yml"
    prefix:   /

farpost_store:
    resource: "@FarpostStoreBundle/Resources/config/routing.yml"
    prefix:   /

farpost_bases:
    path:     /update/{filename}
    defaults: { _controller: FarpostAPIBundle:Default:getFile }

