farpost_moderator:
    resource: "@FarpostModeratorBundle/Resources/config/routing.yml"
    prefix:   /moderator/

#farpost_admin:
#    resource: "@FarpostWebBundle/Resources/config/admin_routing.yml"
#    prefix:   /admin/

farpost_ajax:
    resource: "@FarpostWebBundle/Resources/config/ajax_routing.yml"
    prefix:   /ajax/

#sonata
farpost_admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

#API
#system methods
farpost_bases:
    path: /update/{filename}
    defaults: { _controller: FarpostAPIBundle:System:getFile }

farpost_init_app:
   path:     /init_app
   defaults: { _controller: FarpostAPIBundle:System:initApp }

#version 1
farpost_api:
    resource: "@FarpostAPIBundle/Resources/config/routing_v1.yml"
    prefix:   /method/
#version 2
farpost_api_v2:
    resource: "@FarpostAPIBundle/Resources/config/routing_v2.yml"
    prefix:   /api2/method/