farpost_moderator:
    resource: "@FarpostModeratorBundle/Resources/config/routing.yml"
    prefix:   /moderator/

farpost_admin:
    resource: "@FarpostWebBundle/Resources/config/admin_routing.yml"
    prefix:   /admin/

farpost_ajax:
    resource: "@FarpostWebBundle/Resources/config/ajax_routing.yml"
    prefix:   /ajax/

#some routes were depricated since v2
farpost_api:
    resource: "@FarpostAPIBundle/Resources/config/routing.yml"
    prefix:   /method/

farpost_api_v2:
    resource: "@FarpostAPIBundle/Resources/config/routing_v2.yml"
    prefix:   /v2/method/

farpost_web:
    resource: "@FarpostWebBundle/Resources/config/routing.yml"
    prefix:   /

farpost_bases:
    path:     /update/{filename}
    defaults: { _controller: FarpostAPIBundle:Default:getFile }

