security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    notanadmin: { password: 16ytu91ito, roles: [ 'ROLE_ADMIN' ] }
                    moderator:  { password: moderator, roles: ['ROLE_MODERATOR'] }

    firewalls:
        secured_area:
            pattern: ^/admin
            anonymous: ~
            http_basic:
                realm: "Secured admin area"
        moderator_area:
            pattern: ^/moderator
            anonymous: ~
            http_basic:
                realm: "Secured moderator area"
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        demo_login:
            pattern:  ^/demo/secured/login$
            security: false

        demo_secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _demo_security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - {path: ^/admin, roles: 'ROLE_ADMIN'}
        - {path: ^/moderator, roles: 'ROLE_MODERATOR'}
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }