parameters:
#    farpost_store.example.class: Farpost\StoreBundle\Example

services:
#    farpost_store.example:
#        class: %farpost_store.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
