parameters:
    farpost.maps.graph_importer.class: Farpost\MapsBundle\Services\GraphImporter

services:
    farpost.maps.graph_importer:
        class: %farpost.maps.graph_importer.class%
        arguments: [@doctrine, "%backup_database_user%"]