services:
    sonata.admin.poi_group:
        class: Farpost\POIBundle\Admin\GroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "POI", label: "title.groups" }
        arguments:
            - ~
            - Farpost\POIBundle\Entity\Group
            - ~
        calls:
            - [ setTranslationDomain, [FarpostPOIBundle] ]

    sonata.admin.poi_type:
        class: Farpost\POIBundle\Admin\TypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "POI", label: "title.types" }
        arguments:
            - ~
            - Farpost\POIBundle\Entity\Type
            - ~
        calls:
            - [ setTranslationDomain, [FarpostPOIBundle] ]

    sonata.admin.poi_point:
        class: Farpost\POIBundle\Admin\PointAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "POI", label: "title.points" }
        arguments:
            - ~
            - Farpost\POIBundle\Entity\Point
            - ~
        calls:
            - [ setTranslationDomain, [FarpostPOIBundle] ]