services:
    sonata.admin.catalogue_object:
        class: Farpost\CatalogueBundle\Admin\CatalogueObjectAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Catalogue", label: "title.objects" }
        arguments:
            - ~
            - Farpost\CatalogueBundle\Entity\CatalogueObject
            - ~
        calls:
            - [ setTranslationDomain, [FarpostCatalogueBundle] ]

    sonata.admin.catalogue_category:
        class: Farpost\CatalogueBundle\Admin\CatalogueCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Catalogue", label: "title.categories_and_organisations" }
        arguments:
            - ~
            - Farpost\CatalogueBundle\Entity\CatalogueCategory
            - ~
        calls:
            - [ setTranslationDomain, [FarpostCatalogueBundle] ]

    sonata.admin.catalogue_category_edge:
        class: Farpost\CatalogueBundle\Admin\CatalogueCategoryEdgeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Catalogue", label: "title.catalogue_category_edge", show_in_dashboard: false }
        arguments:
            - ~
            - Farpost\CatalogueBundle\Entity\CatalogueCategoryEdge
            - ~
        calls:
            - [ setTranslationDomain, [FarpostCatalogueBundle] ]

    sonata.admin.catalogue_category_object_edge:
        class: Farpost\CatalogueBundle\Admin\CatalogueCategoryObjectEdgeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Catalogue", label: "title.catalogue_category_object_edge", show_in_dashboard: false }
        arguments:
            - ~
            - Farpost\CatalogueBundle\Entity\CatalogueCategoryObjectEdge
            - ~
        calls:
            - [ setTranslationDomain, [FarpostCatalogueBundle] ]

    sonata.admin.catalogue_category_object_schedule:
        class: Farpost\CatalogueBundle\Admin\CatalogueObjectScheduleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Catalogue", label: "title.catalogue_object_schedule", show_in_dashboard: false }
        arguments:
            - ~
            - Farpost\CatalogueBundle\Entity\CatalogueObjectSchedule
            - ~
        calls:
            - [ setTranslationDomain, [FarpostCatalogueBundle] ]