parameters:
    farpost_catalogue.image_manager.class: Farpost\CatalogueBundle\Services\ImageManager

services:
    farpost_catalogue.image_manager:
        class: %farpost_catalogue.image_manager.class%
        arguments: [@image.handling, @doctrine]
