parameters:
    farpost_catalogue.image_manager.class: Farpost\CatalogueBundle\Services\ImageManager
    farpost_catalogue.catalogue_exporter.class: Farpost\CatalogueBundle\Services\CatalogueExporter
    farpost_catalogue.catalogue_importer.class: Farpost\CatalogueBundle\Services\CatalogueImporter

services:
    farpost_catalogue.image_manager:
        class: %farpost_catalogue.image_manager.class%
        arguments: [@image.handling, @doctrine]

    farpost_catalogue.catalogue_exporter:
        class: %farpost_catalogue.catalogue_exporter.class%
        arguments: [@doctrine, @sqlite_manager, @farpost_store.version_manager, @service_container]

    farpost_catalogue.catalogue_importer:
        class: %farpost_catalogue.catalogue_importer.class%
        arguments: ["%default_database_name%", "%default_database_user%"]

    farpost_catalogue.serializer.category:
        class: Farpost\CatalogueBundle\Serializer\CategorySerializer

    farpost_catalogue.serializer.object:
        class: Farpost\CatalogueBundle\Serializer\ObjectSerializer

    farpost_catalogue.serializer.category_edge:
            class: Farpost\CatalogueBundle\Serializer\CategoryEdgeSerializer

    farpost_catalogue.serializer.category_node_edge:
            class: Farpost\CatalogueBundle\Serializer\CategoryNodeEdgeSerializer
