parameters:
    farpost_catalogue.image_manager.class: Farpost\CatalogueBundle\Services\ImageManager
    farpost_catalogue.catalogue_exporter.class: Farpost\CatalogueBundle\Services\CatalogueExporter

services:
    farpost_catalogue.image_manager:
        class: %farpost_catalogue.image_manager.class%
        arguments: [@image.handling, @doctrine]

    farpost_catalogue.catalogue_exporter:
        class: %farpost_catalogue.catalogue_exporter.class%
        arguments: [@doctrine, @sqlite_manager, @farpost_store.version_manager, @service_container]
