parameters:
#    farpost_news.example.class: Farpost\NewsBundle\Example

services:
#    farpost_news.example:
#        class: %farpost_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
