parameters:
#    farpost_moderator.example.class: Farpost\ModeratorBundle\Example

services:
#    farpost_moderator.example:
#        class: %farpost_moderator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
